[package]
name = "kybe-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
clap = "4.5.54"
anyhow = "1.0.100"
thiserror = "2.0.17"
clap_generate = "3.0.3"
